### ISSUE TITLE
Broken link in readme

### ISSUE THREAD

**Issue by kla-ko** [speechly/speech-recognition-polyfill#34]
### Describe the bug
There is a broken link in the top level readme-file (https://docs.speechly.com/quick-start/stt-only/).

### To Reproduce
1. Click on this link (https://docs.speechly.com/quick-start/stt-only/)
2. A ``Page not found`` page is shown

### Environment
All browsers

**Comment by thisismatu** [comment]
@kla-ko thanks for noticing, will fix! 👍

**Comment by JamesBrill** [comment]
@thisismatu This is still broken - could someone revive the page at that link?

**Comment by JamesBrill** [comment]
Ah apologies, I noticed the README was updated.
